#!/bin/sh

for f in $(find . -type f -and \( -name '*.hh' -or -name '*.cc' -or -name '*.py' \) ) ; do
    # Favor tabulators over blanks.
    unexpand $f >$f.unexpand
    chmod --reference=$f $f.unexpand
    if cmp --quiet $f $f.unexpand; then
        rm $f.unexpand
    else
	mv $f $f~1~
	mv $f.unexpand $f
	echo "fixed tabulators in $f"
    fi

    # There should be no white-space at the end of a line.
    sed 's/[ \x09\x0d]*$//;' $f >$f.rstrip
    chmod --reference=$f $f.rstrip
    if cmp --quiet $f $f.rstrip; then
        rm $f.rstrip
    else
	mv $f $f~2~
	mv $f.rstrip $f
	echo "removed trailing white-space in $f"
    fi

    # There should not be any blank lines at the end of the file
    # .. to be implemented
    
done
